# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Chunk Summary via R and C++
#'
#' Divide the whole dataset into four chunks and calculate the mean and standard deviation of each chunks. An R function calls the C++.
#'
#' @param x A data frame.
#'
#' @return A table is provided, which include the names of each column and the results.
#'
#' @examples
#' library(Rcpp)
#' library(MASS)
#' data<-birthwt
#' sourceCpp("src/chunkSummaryC.cpp")
#' chunkSummaryC(data)
#'
#' @seealso \code{\link[lng]{chunkSummaryR}}
#'
#' @references Hadley Wickham (2015) R package.
#'
#' @export
#'
chunkSummaryC <- function(x) {
    .Call('_lng_chunkSummaryC', PACKAGE = 'lng', x)
}

#' Multiple a number
#'
#' @param x A single number
#' @export
NULL

timesTwo <- function(x) {
    .Call('_lng_timesTwo', PACKAGE = 'lng', x)
}

