# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get the chunkSummary
#'
#' @param x A dataframe.
#' @export
#'
chunkSummaryC <- function(x) {
    .Call('_lng_chunkSummaryC', PACKAGE = 'lng', x)
}

#' Multiple a number
#'
#' @param x A single number
#' @export
NULL

timesTwo <- function(x) {
    .Call('_lng_timesTwo', PACKAGE = 'lng', x)
}

